import React from 'react';

export interface DashboardFooterProps {
  /** Gatling version used for test execution */
  gatlingVersion?: string;
  /** Parser version used for report generation */
  parserVersion?: string;
  /** Additional CSS classes to apply to the footer */
  className?: string;
}

/**
 * DashboardFooter component displays version information and attribution
 * for the performance test report dashboard.
 */
const DashboardFooter: React.FC<DashboardFooterProps> = ({
  gatlingVersion = 'Unknown',
  parserVersion = 'Unknown',
  className = '',
}) => {
  return (
    <footer className={`mt-12 text-center ${className}`}>
      <p className="text-sm text-slate-500">
        Generated By Perf Report 0.0.1 • Test Executed By Gatling {gatlingVersion} • Parser {parserVersion}
      </p>
    </footer>
  );
};

export default DashboardFooter;
